### ISSUE TITLE
No Traffic

### ISSUE THREAD

**Issue by Dabuek** [silentbreaksec/Throwback#1]
After compiling the Throwback executable i ran it within a Windows 7 Home SP1 x64 VM and I didnt see any traffic. I wanted to test the initial beaconing, i didnt change anything - Is there an issue with the client or does the original source code need amending? (i purposefully my encoded IPs out)

**Comment by silentbreaksec** [comment]
Did you run tbManger.py to encode the URL correctly, and add a '-1' to the end of the array?

**Comment by Dabuek** [comment]
Yes, I kept the default 192.168.20.133 in the array;

int DNSCODE[DNSARRAY][DNSCODESIZE] = {{57,37,37,33,34,107,126,126,96,104,99,127,96,103,105,127,99,97,127,96,98,98,126,56,63,53,52,41,127,33,57,33,-1}, {57,37,37,33,34,107,126,126,96,104,99,127,96,103,105,127,99,97,127,96,98,98,126,56,63,53,52,41,127,33,57,33,-1}};
